name: Danrods.com
title: Dan Rodrigues
lsi: false
safe: false
incremental: false
gist:
  noscript: false
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
twitter:
  card: summary
  username: danxrods
url: https://danrods.com
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag
  - kramdown
  - jekyll-feed